title: Lionel Jouin
description: >- # this means to ignore newlines until "baseurl:"
  Description
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lioneljouin.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
github_username: LionelJouin
linkedin_username: lioneljouin

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
